In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df= pd.read_csv("Churn_Modelling.csv")

In [2]:
df2 = df.copy()
df2.loc[0:53, 'Gender'] = np.nan
df2.loc[38:337, 'Age'] = np.nan

In [3]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           9946 non-null   str
 6   Age              9700 non-null   float64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), str(3)
memory usage: 1.1 MB

In [4]:
df2.drop(columns=["CustomerId", "Surname","RowNumber"], inplace=True)

In [5]:
df2.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,NaN,42.0,2,0.00,1,1,1,101348.88,1
1,608,Spain,NaN,41.0,1,83807.86,1,0,1,112542.58,0
2,502,France,NaN,42.0,8,159660.80,3,1,0,113931.57,1
3,699,France,NaN,39.0,1,0.00,2,0,0,93826.63,0
4,850,Spain,NaN,43.0,2,125510.82,1,1,1,79084.10,0

In [6]:
df2.Gender.value_counts()

Gender
Male      5431
Female    4515
Name: count, dtype: int64

In [8]:
df2['Gender']= df2['Gender'].fillna('Male')
df2.Gender.value_counts()

Gender
Male      5485
Female    4515
Name: count, dtype: int64

In [9]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  str
 2   Gender           10000 non-null  str
 3   Age              9700 non-null   float64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(3), int64(6), str(2)
memory usage: 859.5 KB

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df2['Gender_label']= le.fit_transform(df2.Gender.values)

In [27]:
df2_dummies= pd.get_dummies(df2)
df2_dummies.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Gender_label,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42.0,2,0.00,1,1,1,101348.88,1,1,True,False,False,False,True
1,608,41.0,1,83807.86,1,0,1,112542.58,0,1,False,False,True,False,True
2,502,42.0,8,159660.80,3,1,0,113931.57,1,1,True,False,False,False,True
3,699,39.0,1,0.00,2,0,0,93826.63,0,1,True,False,False,False,True
4,850,43.0,2,125510.82,1,1,1,79084.10,0,1,False,False,True,False,True